---
vault_version: "1.18.3"
vault_user: "vault"
vault_group: "vault"

vault_config_dir: "/etc/vault.d"
vault_data_dir: "/opt/vault/data"
vault_tls_dir: "/etc/vault.d/tls"
vault_log_dir: "/var/log/vault"

vault_api_port: 8200
vault_cluster_port: 8201

vault_local_credentials_dir: "{{ lookup('env', 'CI_PROJECT_DIR') | default(playbook_dir ~ '/..', true) }}/credentials"
